### PR TITLE
Break down task health check into two variables

### PR DESCRIPTION
**Pull request by Ohid25**
# Description

`task_health_check` broken down into two variables with conditions in place too.

### CODE REVIEW

**Review by Mohammed-afk91 — APPROVED** [review]

**Comment by sorinpop-ri** [comment]
This breaks old deployments that do not provide task_health_check (it is listed as optional)

**Comment by sorinpop-dn** [comment]
This breaks old deployments that do not provide task_health_check (it is listed as optional)

**Comment by Ohid25** [comment]
Can you try the new [6.4.1](https://github.com/umotif-public/terraform-aws-ecs-fargate/releases/tag/6.4.1) release? The fix I made straight after this PR should fix your above problem.

**Comment by sorinpop-dn** [comment]
The way it is defined now you need task_health_check defined but in the examples it is missing. 
This is the error I'm getting:

│ Error: Invalid function argument
│ 
│   on .terraform/modules/fargate/main.tf line 195, in resource "aws_ecs_task_definition" "task":
│  195:     "interval": ${lookup(var.task_health_check, "interval", 30)},
│     ├────────────────
│     │ var.task_health_check is null
│ 
│ Invalid value for "inputMap" parameter: argument must not be null.

**Comment by Ohid25** [comment]
This [example](https://github.com/umotif-public/terraform-aws-ecs-fargate/blob/master/examples/core/main.tf#L111) has `task_health_check` defined. I've also tried the other example, where `task_health_check` isn't defined. Both work. 

Can you show me the example config/code you have that is causing the error?

**Pull request merged**
