### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mandrean**

### CODE REVIEW

**Comment by Ohid25** [comment]
Hi @mandrean - brilliant find! Thank you.

I've managed to test this locally on our projects and it seems to be fine. Can you please rebase this PR against master + run `make changelog` and then I can merge this change in?

**Comment by mandrean** [comment]
Hi @Ohid25! Sorry for late reply. So easy to miss relevant GH notifications with all that noise.

Rebased + pushed

**Review by Ohid25 — APPROVED** [review]
LGTM

**Comment by Ohid25** [comment]
Thanks for the contribution @mandrean! This is now released as [6.5.1](https://github.com/umotif-public/terraform-aws-ecs-fargate/releases/tag/6.5.1).

**Pull request merged**
