### PR TITLE
created json file and assign into main.tf file . for a better terraform file 

### PR DESCRIPTION
**Pull request by satyamuralidhar**
# Description

Please explain the changes you made here and link to any relevant issues.
created json file and assign into main.tf file . for a better terraform file  to easy understanding for users

### CODE REVIEW

**Comment by Ohid25** [comment]
Hi, I just tried testing this change with one of the examples in the repository.

`❯ terraform validate
Warning: Interpolation-only expressions are deprecated
  on ../../main.tf line 153, in resource "aws_ecs_task_definition" "task":
 153:   container_definitions =  ["${file(container_definitions.json)}"]
Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.
Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.
Error: Reference to undeclared resource
  on ../../main.tf line 153, in resource "aws_ecs_task_definition" "task":
 153:   container_definitions =  ["${file(container_definitions.json)}"]
A managed resource "container_definitions" "json" has not been declared in
module.fargate.`

**Comment by Ohid25** [comment]
I am sorry, but the change you just pushed did not work too. 

Can you please use the examples within the repository to test out your change and show that the change you are trying to implement works?

**Comment by satyamuralidhar** [comment]
pls check with this if not working close the request i will try after some time

**Comment by satyamuralidhar** [comment]
and also please add me as a member bro .

**Pull request closed without merging**
